"""
Django settings for deai project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
# from django.core.cache import cache
from pathlib import Path
from django import apps
from django.apps import *
import os, sys
import channels
from . import config
from channels.routing import ProtocolTypeRouter 
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

SECRET_KEY = '' ## django key
RIOT_API_KEY = '' ## your riot api key
RIOT_DD_VERSION = '16.5.1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# ALLOWED_HOSTS = ['localhost', '127.0.0.1']
ALLOWED_HOSTS = [''] ## * <- 배포 시 해제 
# ngrok HTTPS 헤더 신뢰
CSRF_TRUSTED_ORIGINS = ['']
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # ngrok/배포 시에만 활성화
# Application definition

INSTALLED_APPS = [
    #'score',
    'channels',
    "deai_project",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "riot-cache"
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'deai.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'deai_project' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'deai.wsgi.application'
ASGI_APPLICATION = 'deai.asgi.application'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3', ## self
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}
# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr' ## self

TIME_ZONE = 'Asia/Seoul' ## self

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL  = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')  # collectstatic 결과물 위치
STATICFILES_DIRS = [
    # os.path.join(BASE_DIR, 'static'),  # 원본 static 파일 위치
     BASE_DIR / 'deai_project' / 'static',
]

SESSION_COOKIE_SAMESITE = 'Lax'
SESSION_COOKIE_SECURE   = False
CSRF_COOKIE_SAMESITE    = 'Lax'
CSRF_COOKIE_SECURE      = False

CSRF_TRUSTED_ORIGINS = [

]
# 이메일 설정 (Gmail SMTP)
EMAIL_BACKEND       = 
EMAIL_HOST          = 
EMAIL_PORT          = 
EMAIL_USE_TLS       = True
EMAIL_HOST_USER     = 
EMAIL_HOST_PASSWORD =  
DEFAULT_FROM_EMAIL  = EMAIL_HOST_USER

RIOT_REGION_MAP = {

}

VAL_TIER_MAP = {

}

VAL_QUEUE_MAP = {

}

VAL_MAP_MAP = {

}

VAL_AGENT_MAP = {

}
