# Generated by Django 6.0.2 on 2026-03-08 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseUserInformation_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='닉네임')),
                ('password', models.CharField(max_length=256, verbose_name='비밀번호')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_dms', to='deai_project.baseuserinformation_data')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_dms', to='deai_project.baseuserinformation_data')),
            ],
            options={
                'db_table': 'direct_message',
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '대기 중'), ('accepted', '수락됨'), ('rejected', '거절됨')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='deai_project.baseuserinformation_data')),
            ],
            options={
                'db_table': 'join_request',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('join_request', '가입 요청'), ('join_accept', '가입 수락'), ('join_reject', '가입 거절')], max_length=20)),
                ('message', models.CharField(max_length=200)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_join_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='deai_project.joinrequest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='deai_project.baseuserinformation_data')),
            ],
            options={
                'db_table': 'notification',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post_Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(choices=[('lol', '리그 오브 레전드'), ('val', '발로란트'), ('ow', '오버워치 2'), ('fifa', '피파 온라인 4'), ('genshin', '원신')], max_length=10, verbose_name='게임')),
                ('post_title', models.CharField(max_length=100, verbose_name='제목')),
                ('post_body', models.TextField(blank=True, verbose_name='한마디')),
                ('current_member', models.IntegerField(default=1, verbose_name='현재 인원')),
                ('total_member', models.IntegerField(default=5, verbose_name='모집 인원')),
                ('tier_condition', models.CharField(default='무관', max_length=20, verbose_name='티어 조건')),
                ('is_open', models.BooleanField(default=True, verbose_name='모집 중')),
                ('post_upload_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='deai_project.baseuserinformation_data', verbose_name='작성자')),
            ],
            options={
                'db_table': 'user_post_circuit',
                'ordering': ['-post_upload_at'],
            },
        ),
        migrations.AddField(
            model_name='joinrequest',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='deai_project.post_community'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='deai_project.baseuserinformation_data')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='deai_project.post_community')),
            ],
            options={
                'db_table': 'chat_message',
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('detail', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to='deai_project.baseuserinformation_data')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_sent', to='deai_project.baseuserinformation_data')),
            ],
            options={
                'db_table': 'user_report',
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '대기 중'), ('accepted', '수락됨'), ('rejected', '거절됨')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='deai_project.baseuserinformation_data', verbose_name='요청자')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='deai_project.baseuserinformation_data', verbose_name='수신자')),
            ],
            options={
                'db_table': 'friendship',
                'unique_together': {('from_user', 'to_user')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='joinrequest',
            unique_together={('post', 'user')},
        ),
        migrations.CreateModel(
            name='PostParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='deai_project.post_community', verbose_name='게시글')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_posts', to='deai_project.baseuserinformation_data', verbose_name='참여자')),
            ],
            options={
                'db_table': 'post_participant',
                'unique_together': {('post', 'user')},
            },
        ),
        migrations.CreateModel(
            name='UserPreferGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(choices=[('lol', '리그 오브 레전드'), ('val', '발로란트'), ('ow', '오버워치 2'), ('fifa', '피파 온라인 4'), ('genshin', '원신')], max_length=10, verbose_name='게임')),
                ('name_tag', models.CharField(max_length=50, verbose_name='Name#Tag')),
                ('tier', models.CharField(blank=True, max_length=20, verbose_name='티어')),
                ('score_best', models.IntegerField(default=0, verbose_name='최고 점수')),
                ('score_current', models.IntegerField(default=0, verbose_name='현재 점수')),
                ('sub_info', models.CharField(blank=True, max_length=30, verbose_name='포지션/역할')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefer_games', to='deai_project.baseuserinformation_data', verbose_name='유저')),
            ],
            options={
                'db_table': 'user_prefer_game',
                'unique_together': {('user', 'game_id')},
            },
        ),
    ]
