# Generated by Django 6.0.2 on 2026-03-02 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deai_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(choices=[('lol', '리그 오브 레전드'), ('val', '발로란트'), ('ow', '오버워치 2'), ('fifa', '피파 온라인 4'), ('genshin', '원신')], max_length=10, verbose_name='게임')),
                ('name_tag', models.CharField(max_length=50, verbose_name='Name#Tag')),
                ('tier', models.CharField(blank=True, max_length=20, verbose_name='티어')),
                ('score_best', models.IntegerField(default=0, verbose_name='최고 점수')),
                ('score_current', models.IntegerField(default=0, verbose_name='현재 점수')),
                ('sub_info', models.CharField(blank=True, max_length=30, verbose_name='포지션/역할')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefer_games', to='deai_project.baseuserinformation_data', verbose_name='유저')),
            ],
            options={
                'db_table': 'user_prefer_game',
                'unique_together': {('user', 'game_id')},
            },
        ),
    ]
