# Generated by Django 6.0.2 on 2026-03-02 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deai_project', '0002_userprefergame'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post_Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(choices=[('lol', '리그 오브 레전드'), ('val', '발로란트'), ('ow', '오버워치 2'), ('fifa', '피파 온라인 4'), ('genshin', '원신')], max_length=10, verbose_name='게임')),
                ('post_title', models.CharField(max_length=100, verbose_name='제목')),
                ('post_body', models.TextField(blank=True, verbose_name='한마디')),
                ('current_member', models.IntegerField(default=1, verbose_name='현재 인원')),
                ('total_member', models.IntegerField(default=5, verbose_name='모집 인원')),
                ('tier_condition', models.CharField(default='무관', max_length=20, verbose_name='티어 조건')),
                ('is_open', models.BooleanField(default=True, verbose_name='모집 중')),
                ('post_upload_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='deai_project.baseuserinformation_data', verbose_name='작성자')),
            ],
            options={
                'db_table': 'user_post_circuit',
                'ordering': ['-post_upload_at'],
            },
        ),
    ]
