# Generated by Django 6.0.2 on 2026-03-05 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deai_project', '0007_joinrequest_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_dms', to='deai_project.baseuserinformation_data')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_dms', to='deai_project.baseuserinformation_data')),
            ],
            options={
                'db_table': 'direct_message',
                'ordering': ['sent_at'],
            },
        ),
    ]
