# Generated by Django 6.0.2 on 2026-03-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deai_project', '0009_userreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuserinformation_data',
            name='blocked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userreport',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
