# Generated by Django 6.0.2 on 2026-03-08 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deai_project', '0003_post_community'),
        ('deai_project', '0010_baseuserinformation_data_blocked_until_and_more'),
    ]

    operations = [
    ]
