# Generated by Django 6.0.2 on 2026-03-19 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deai_project', '0011_merge_20260308_1859'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiotDataCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=120, unique=True, verbose_name='캐시 키')),
                ('data', models.JSONField(verbose_name='JSON 데이터')),
                ('version', models.CharField(blank=True, default='', max_length=20, verbose_name='데이터 버전(패치)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='최초 저장')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='최근 갱신')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='만료 시각 (null=영구)')),
            ],
            options={
                'verbose_name': 'Riot 데이터 캐시',
                'db_table': 'riot_data_cache',
            },
        ),
    ]
