# Generated by Django 6.0.2 on 2026-03-20 09:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deai_project', '0012_riotdatacache'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('lol', 'League of Legends'), ('tft', 'Teamfight Tactics')], max_length=5)),
                ('queue', models.CharField(choices=[('RANKED_SOLO_5x5', 'LoL 솔로랭크'), ('RANKED_FLEX_SR', 'LoL 자유랭크'), ('RANKED_TFT', 'TFT 솔로'), ('RANKED_TFT_DOUBLE_UP', 'TFT 더블업')], max_length=30)),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='수집 시각')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 스냅샷')),
            ],
            options={
                'db_table': 'c_ranking_snapshot',
                'indexes': [models.Index(fields=['game', 'queue', 'is_active'], name='c_ranking_s_game_936ced_idx')],
            },
        ),
        migrations.CreateModel(
            name='RankingEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(verbose_name='순위')),
                ('summoner_id', models.CharField(blank=True, max_length=100)),
                ('puuid', models.CharField(blank=True, db_index=True, max_length=100)),
                ('name', models.CharField(default='?', max_length=80)),
                ('tag_line', models.CharField(blank=True, max_length=20)),
                ('icon_id', models.PositiveIntegerField(default=1)),
                ('level', models.PositiveIntegerField(default=1)),
                ('tier', models.CharField(max_length=20)),
                ('division', models.CharField(blank=True, max_length=4)),
                ('rank_label', models.CharField(max_length=30)),
                ('lp', models.IntegerField(default=0)),
                ('wins', models.IntegerField(default=0)),
                ('losses', models.IntegerField(default=0)),
                ('winrate', models.IntegerField(default=0)),
                ('hot_streak', models.BooleanField(default=False)),
                ('veteran', models.BooleanField(default=False)),
                ('fresh_blood', models.BooleanField(default=False)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='deai_project.rankingsnapshot')),
            ],
            options={
                'db_table': 'c_userTable',
                'ordering': ['rank'],
                'indexes': [models.Index(fields=['snapshot', 'rank'], name='c_userTable_snapsho_bb1d1b_idx')],
            },
        ),
    ]
