# Generated by Django 6.0.2 on 2026-03-03 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deai_project', '0003_post_community'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='deai_project.post_community', verbose_name='게시글')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joined_posts', to='deai_project.baseuserinformation_data', verbose_name='참여자')),
            ],
            options={
                'db_table': 'post_participant',
                'unique_together': {('post', 'user')},
            },
        ),
    ]
